Processing git secrets output

diff --git a/.github/workflows/check_secrets.yml b/.github/workflows/check_secrets.yml
--- a/.github/workflows/check_secrets.yml
+++ b/.github/workflows/check_secrets.yml
@@ -23,7 +23,12 @@ jobs:
           echo installing git-secrets
           sudo make install
           git secrets --register-aws --global
-          git secrets --scan-history
+          secretsOutput="$(git secrets --scan-history 2>&1)"
+          if echo "$secretsOutput" | grep -c ERROR; then
+            exit 1
+          else
+            exit 0
+          fi
 
 
   slack-workflow-status:
