Testing Check Secrets workflow

diff --git a/.github/workflows/check_secrets.yml b/.github/workflows/check_secrets.yml
--- a/.github/workflows/check_secrets.yml
+++ b/.github/workflows/check_secrets.yml
@@ -24,10 +24,12 @@ jobs:
           sudo make install
           git secrets --register-aws --global
           secretsOutput="$(git secrets --scan-history 2>&1)"
-          echo "$secretsOutput"
-          
-          return `echo "$secretsOutput" | grep -c ERROR`
-          
+          if echo "$secretsOutput" | grep -c ERROR; then
+            exit 1
+          else
+            exit 0
+          fi
+
 
   slack-workflow-status:
     if: failure()
